# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github' do
  use_frameworks!
  pod 'APIKit', '~> 3.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Himotoki'
  pod 'PINRemoteImage'
end
